//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Sold_Items = new HashSet<Sold_Items>();
        }
    
        public int Id { get; set; }
        public string Payment_type { get; set; }
        public string Destination { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual ICollection<Sold_Items> Sold_Items { get; set; }
    }
}
