//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Payments = new HashSet<Payment>();
            this.ProductInventories = new HashSet<ProductInventory>();
            this.TrackOrders = new HashSet<TrackOrder>();
        }
    
        public int Id { get; set; }
        public string BookName { get; set; }
        public string BookCondition { get; set; }
        public string Category { get; set; }
        public string Book_details { get; set; }
        public string Author_Name { get; set; }
        public int SellerID { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual ICollection<TrackOrder> TrackOrders { get; set; }
    }
}
