//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public Registration()
        {
            this.Payments = new HashSet<Payment>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string uname { get; set; }
        public string gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string user_type { get; set; }
        public string shop_name { get; set; }
        public string password { get; set; }
        public string confirm_password { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
